# Google App Engine app configuration
runtime: go113

env_variables:
  CONSUMER_ENDPOINT: "https://stellar-ether-256523.appspot.com//"
  RESULTS_DIR: "/tmp/producer/"
main: github.com/rafaelkperes/tcc/cmd/producer
manual_scaling:
  instances: 1